name: python-ekyc

dependencies:
  - python=3.8
  - pip
  - pip:
      - dlib==19.24.2
      - easydict==1.9
      - numpy==1.24.3
      - opencv_python==4.2.0.34
      - Pillow==7.1.2
      - protobuf==3.20
      - tensorboardX==2.0
      - torchvision==0.16.1
      - tqdm==4.31.1